---
title: "Paper Summary"
author: "Marqus Odisho & Sargon Yousefian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages('ggplot2')
#install.packages('lme4')
#install.packages('lmerTest')
#install.packages('MuMIn')
#install.packages('MASS')
#install.packages('dplyr')
#install.packages('tidyr')
#install.packages('car')
#install.packages('pbkrtest')
#install.packages('pscl')
library(ggplot2)
library(lme4)
library(lmerTest)
library(MuMIn)
library(MASS)
library(dplyr)
library(tidyr)
library(car)
library(pbkrtest)
library(pscl)
```
## Data Simulation & Analysis
### Assay 1:
For the data 
```{r Assay 1: Figure 1a. Data Simulation & Analysis}
# Set the number of replicates from paper
n_vials <- 10

# Set the average differences in activity scores
mean_diff_simple <- 6
mean_diff_complex <- -1

# Adjust the standard deviation to achieve the desired t-value and p-value
sd_diff <- 2.5

# Create an empty data frame
activity_data <- data.frame(
  female_type = character(0),
  arena_type = character(0),
  vial_cage_id = numeric(0),
  activity_score = numeric(0)
)

# Generate data for each vial/cage (for loops are harder in R than in Python in my opinion!)
for (i in 1:n_vials) {
  # Simple arena
  activity_data <- rbind(activity_data, data.frame(
    female_type = "large",
    arena_type = "simple",
    vial_cage_id = i,
    activity_score = rnorm(1, mean = 10 + mean_diff_simple/2, sd = sd_diff)
  ))
  activity_data <- rbind(activity_data, data.frame(
    female_type = "small",
    arena_type = "simple",
    vial_cage_id = i,
    activity_score = rnorm(1, mean = 10 - mean_diff_simple/2, sd = sd_diff)
  ))

  # Complex arena
  activity_data <- rbind(activity_data, data.frame(
    female_type = "large",
    arena_type = "complex",
    vial_cage_id = i,
    activity_score = rnorm(1, mean = 10 + mean_diff_complex/2, sd = sd_diff)
  ))
  activity_data <- rbind(activity_data, data.frame(
    female_type = "small",
    arena_type = "complex",
    vial_cage_id = i,
    activity_score = rnorm(1, mean = 10 - mean_diff_complex/2, sd = sd_diff)
  ))
}

# Calculate the difference in activity scores within each vial/cage
activity_data <- activity_data %>%
  group_by(arena_type, vial_cage_id) %>%
  summarize(score_difference = activity_score[female_type == "large"] - activity_score[female_type == "small"])

# Perform the two-sample t-test 
t.test(score_difference ~ arena_type, data = activity_data)

```

```{r test}
# Simulate Trait of Interest
rnorm(1000, 10, 1)->trait_of_interest ### change this to be a trait that you're actually interested in, with an appropriate distribution! 

plot(density(trait_of_interest))
min(trait_of_interest)
max(trait_of_interest)

yes<-sample(trait_of_interest, 500, replace=FALSE, prob = ifelse(trait_of_interest>0, 0.95, 0.15)) #### play with this line! Is the test statistically significant. When is it not?
predictor_t.test<-(trait_of_interest %in% yes)

cbind.data.frame(trait_of_interest, predictor_t.test)->data

mean(data[which(data$predictor_t.test==TRUE),1])
mean(data[which(data$predictor_t.test==FALSE),1])
t.test(trait_of_interest~predictor_t.test, data=data) ### this does a two sample t-test. What would a one sample t test be testing? How would you do that?

### plots our two samples for distribution
plot(density(data[which(data$predictor_t.test==FALSE),1]), col="red", main="Two sample t test")
lines(density(data[which(data$predictor_t.test==TRUE),1]), ylim=c(0, 0.1), xlim=c(-20,20), main="Two Sample T test")

test1<-sample(trait_of_interest, 200, replace=FALSE, prob = ifelse(trait_of_interest>7, 0.95, 0.15))
test2<-sample(trait_of_interest[which(trait_of_interest %in% test1 == FALSE)], 200, replace=FALSE, prob = ifelse(trait_of_interest[which(trait_of_interest %in% test1 == FALSE)] >4, 0.95, 0.15))
test3<-sample(trait_of_interest[which(trait_of_interest %in% test2 == FALSE | trait_of_interest %in% test1 ==FALSE)], 200, replace=FALSE, prob = ifelse(trait_of_interest[which(trait_of_interest %in% test2 == FALSE | trait_of_interest %in% test1 == FALSE)] >0, 0.95, 0.15))
test4<-sample(trait_of_interest[which(trait_of_interest %in% test2 == FALSE | trait_of_interest %in% test1 ==FALSE | trait_of_interest %in% test3 == FALSE)], 200, replace=FALSE, prob = ifelse(trait_of_interest[which(trait_of_interest %in% test2 == FALSE | trait_of_interest %in% test1 ==FALSE | trait_of_interest %in% test3 == FALSE)] >-4, 0.95, 0.15))
test5<-trait_of_interest[which(trait_of_interest %in% test1 == FALSE| trait_of_interest %in% test2 == FALSE | trait_of_interest %in% test3 == FALSE | trait_of_interest %in% test4 == FALSE)]


plot(density(test1), ylim=c(0, 0.1), main="Anovas")
lines(density(test2), col="red")
lines(density(test3), col="blue")
lines(density(test4), col="purple")
lines(density(test5), col="yellow")


anova_predictor<-data.frame(ifelse(trait_of_interest %in% test1 == TRUE, "group1", ifelse(trait_of_interest %in% test2 == TRUE, "group2", ifelse(trait_of_interest %in% test3 == TRUE, "group3", ifelse(trait_of_interest %in% test4 == TRUE, "group4", "group5")))))

data2<-cbind.data.frame(data, anova_predictor)
names(data2)<-c("trait_of_interest", "predictor_t.test", "anova_predictor")


anova(aov(trait_of_interest~anova_predictor, data=data2)) ### what does this do?

anova(lm(trait_of_interest~anova_predictor, data=data2)) ### what does this do? 
summary(aov(trait_of_interest~anova_predictor, data=data2)) ### what does this do? What do you notice about the last three tests?

```


```{r Assay 1: Figure 1a. Plot}
# Trait of Interest: 

# Sample Data (replace with your actual data)
data <- data.frame(
  Environment = factor(rep(c('Vial', 'Cage'), each = 2), levels = c('Vial', 'Cage')),
  Size = factor(rep(c('Small', 'Large'), 2), levels = c('Small', 'Large')),
  Mean = c(4, 10, 6, 5),
  SD = c(1, 1, 1, 1)  # Standard deviation (replace with your actual values)
)

# Create the bar graph with error bars (Environment on x-axis)
ggplot(data, aes(x = Environment, y = Mean, fill = Size)) + scale_y_continuous(breaks=c(0, 2, 4, 6, 8, 10)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  geom_errorbar(aes(ymin = Mean - SD, ymax = Mean + SD), 
                width = 0.2, position = position_dodge(0.9)) +
  labs(
    title = '(a)',
    x = '',
    y = "Average Number of Sexual Interactions in a 1 Minute Period",
    fill = ' ' 
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = 'bottom',
    panel.border = element_rect(colour = 'black', fill = NA)
  ) +
  scale_fill_manual(values = c('#B6D0E2', '#F1E3D3'))  # Pastel blue and yellow for the legend
```

```{r Assay 1: Figure 1b. Data Simulation & Analysis}
# RNG time! - Let's keep it consistent 
set.seed(123)

# Number of observations made - 2 females, 3 times a day for 3 days * ten replicates for each arena = 180 observations per environment type.
N = 180

# Changing the effect sizes to get the same values as the paper
effect_arena <- 2.0       # Main effect of Arena
effect_size <- 0.5        # Main effect of Size
effect_interaction <- 2.0  # Interaction effect

# Data simulation time! - Different means for different groups
feeding_count <- c(
  rnorm(N, mean = 6.5, sd = 1), # Large females in vials
  rnorm(N, mean = 13.5 + effect_arena, sd = 1), # Large females in cages
  rnorm(N, mean = 10 + effect_size, sd = 1), # Small females in vials
  rnorm(N, mean = 8.5 + effect_arena + (effect_size * (1 + effect_interaction)), sd = 1) # Small females in cages
)

# Making sure that FeedingCount is a positive float (can't eat negative amounts!)
feeding_count <- ifelse(feeding_count <= 0, feeding_count + 0.1, feeding_count)

# Let's make all of this into a data frame - matrix time :(
data <- data.frame(
  Arena = factor(rep(c('vial', 'cage'), each = N * 2)),
  Size = factor(rep(c('large', 'small'), times = N * 2)),
  FeedingCount = feeding_count
)


model_gaussian <- glm(FeedingCount ~ Arena * Size, data = data, family = gaussian(link = 'log'))

summary(model_gaussian)

# Use lmerTest to get F-statistics and p-values
anova_result <- anova(model_gaussian, test = "F") 

# Print the results
print(anova_result)

```

```{r Assay 1: Figure 1b. Plot}

# Spawning and simulating useful variables to create the plot for Figure 1b
MeanFeeding_Small<-c(10, 9)
MeanFeeding_Large<-c(6.5, 13.5)
EnvironmentType<-c('Vial', 'Cage')
x <- c(1, 2)
SD = c(1, 1, 1, 1)

# Creating a plot that is similar to Figure 1b. in the paper
plot(MeanFeeding_Small, axes = FALSE, xlab= "Mating Arena", ylab="Average Number of Feedings Observed", ylim = c(4, 16), pch = 15, col = '#B6D0E2', type = 'o', lwd = 2, cex = 1.5)
  axis(2)
  axis(1, at = seq_along(MeanFeeding_Small), labels = as.character(EnvironmentType), las = 0)
  lines(c(1, 2), MeanFeeding_Large, col='#F1E3D3', pch = 17, type = 'o', lty = 2, lwd = 2, cex = 1.5)
  title(main = '(b)')

  # Vertical error bars the good ole fashion way
  arrows(x0 = x, y0 = MeanFeeding_Small - SD, x1 = x, y1 = MeanFeeding_Small + SD, code = 3, angle = 90, 
         length = 0.1)
  arrows(x0 = x, y0 = MeanFeeding_Large - SD, x1 = x, y1 = MeanFeeding_Large + SD, code = 3, angle = 90, 
         length = 0.1)

  # Creating a legend that labels the female size types with different colours - corresponds to the colours in      the previous graph
  legend('topleft', inset = 0.05, c('Small', 'Large'), lty = c(1, 2), col =c ('#B6D0E2','#F1E3D3'), 
         lwd = 2, title = "Female Size")

  # Turn plot outline into a box to make it more cutesy
  box()
```

```{r Assay 2: Figure 2. Data Simulation & Analysis}
low.vial<-rnorm(35, 1, 0.1)
high.vial<-rnorm(35, 1, 0.1)
low.cage<-rnorm(35, 1, 0.1)
high.cage<-rnorm(35, 1, 0.1)
g<-sample(1:4, 140, replace=TRUE)
error<-ifelse(g==1, 0.1, ifelse(g==2, 0.5, 1.5))
g<-as.factor(g)
response<-24*low.vial+17*high.vial+30*low.cage+28*high.cage+rnorm(140, mean=0, sd=0.1)
data<-cbind.data.frame(response, low.vial, high.vial, low.cage, high.cage)
model1<-glm(response~low.vial+high.vial+low.cage+high.cage, data=data)
summary(model1)
anova(model1)
```
